//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vis_satan.rc
//
#define IDD_ANALYZER                    1
#define IDS_PLUGIN_NAME                 1
#define IDD_COLOUR                      2
#define IDD_FUNCTION                    3
#define IDD_STYLE                       4
#define IDD_SAVEOPTIONS                 5
#define IDD_PROFILESELECT               6
#define IDM_POPUP                       7
#define IDC_BARSTYLE                    101
#define IDC_FALLOFF                     101
#define IDC_BITMAP_RAMP                 101
#define IDC_COMBOPROFILE                101
#define IDC_PROFILELIST                 101
#define IDC_NATLOG                      101
#define IDC_STATICTEXT1B                102
#define IDC_STATICTEXT1                 102
#define IDC_LEVELGRAPH                  102
#define IDC_CLASSIC                     102
#define IDC_LEFTSELECT                  102
#define IDC_LOAD                        102
#define IDC_STATICMESSAGE               103
#define IDC_SAVE                        103
#define IDC_RIGHTSELECT                 103
#define IDC_PEAKCHANGE                  103
#define IDC_FIRE                        103
#define IDC_SET                         103
#define IDC_STATICTEXT2                 104
#define IDC_LINES                       104
#define IDC_CLOSE                       104
#define IDC_ADD                         104
#define IDC_GROUPSET                    104
#define IDC_DELETE                      105
#define IDC_FALLOFFVAL                  105
#define IDC_WINAMPFIRE                  105
#define IDC_FUNCTIONGROUP               105
#define IDC_PEAK                        105
#define IDC_PEAKCHANGEVAL               106
#define IDC_LOG10                       106
#define IDC_RANDOM                      106
#define IDC_LEFTVAL                     106
#define IDC_RIGHTVAL                    107
#define IDC_BACKGROUND                  107
#define IDC_LOG20                       107
#define IDC_LOG30                       108
#define IDC_BG_BLACK                    108
#define IDC_BITMAP_LEFT                 108
#define IDC_BITMAP_RIGHT                109
#define IDC_LINEAR                      109
#define IDC_BG_SOLID                    109
#define IDC_BG_FLASH                    110
#define IDC_LOG100                      110
#define IDC_STATICTEXT14                110
#define IDC_STATICTEXT7                 111
#define IDC_SINE                        111
#define IDC_PEAKSTYLE                   111
#define IDC_PEAKFADE                    112
#define IDC_SQRT                        112
#define IDC_STATICTEXT8                 112
#define IDC_STATICTEXT9                 113
#define IDC_1OVERX                      113
#define IDC_LEFTRVAL                    113
#define IDC_PEAKLEVEL                   113
#define IDC_PEAKLEVELFADE               114
#define IDC_STATICTEXT10                114
#define IDC_XSQUARED                    114
#define IDC_LEFTGVAL                    114
#define IDC_LEFTBVAL                    115
#define IDC_AVERAGE                     115
#define IDC_BANDWIDTH                   115
#define IDC_BG_GRID                     115
#define IDC_STATICTEXT17                116
#define IDC_XSPACE                      116
#define IDC_ELEVATOR                    116
#define IDC_YSPACE                      117
#define IDC_FREQBARS                    117
#define IDC_VOLUME                      118
#define IDC_STATICTEXT18                119
#define IDC_STATICTEXT12                120
#define IDC_GROUPDRAWORDER              121
#define IDC_RIGHTRVAL                   121
#define IDC_REVERSELEFT                 122
#define IDC_RIGHTGVAL                   122
#define IDC_REVERSERIGHT                123
#define IDC_RIGHTBVAL                   123
#define IDC_BG_FLASHGRID                124
#define IDC_LEVELBASE                   124
#define IDC_LEFTGET                     124
#define IDC_LEFTPUT                     125
#define IDC_GROUPDRAWEFFECT             125
#define IDC_BASE_UNION                  125
#define IDC_BASE_AVERAGE                126
#define IDC_EFFECT_NONE                 126
#define IDC_RIGHTGET                    126
#define IDC_RIGHTPUT                    127
#define IDC_MONO                        127
#define IDC_EFFECT_MIRROR               127
#define IDC_EFFECT_REFLECTION           128
#define IDC_GROUPFFT                    128
#define IDC_FADE                        128
#define IDC_EFFECT_SHADOW               129
#define IDC_FFTENVELOPE                 129
#define IDC_RED                         129
#define IDC_BITMAP_CURCOLOUR            130
#define IDC_FFTENVELOPEVAL              130
#define IDC_EFFECT_DSHADOW              130
#define IDC_FFTSCALE                    131
#define IDC_STATICTEXT20                131
#define IDC_EFFECT_SMOKE                131
#define IDC_FFTSCALEVAL                 132
#define IDC_EFFECT_WAVES                132
#define IDC_REDVAL                      132
#define IDC_GREENVAL                    133
#define IDC_FFTEQUALIZE                 133
#define IDC_GROUPPEAKCOLOUR             133
#define IDC_LATENCYSTATIC               134
#define IDC_STATICTEXT23                134
#define IDC_GROUPPEAKMOTION             134
#define IDC_BLUEVAL                     135
#define IDC_LATENCY                     135
#define IDC_PEAKEFFECT_NORMAL           135
#define IDC_PEAKEFFECT_FALL             136
#define IDC_LATENCYVAL                  136
#define IDC_GREEN                       136
#define IDC_BLUE                        137
#define IDC_PEAKEFFECT_RISE             137
#define IDC_GROUPBOX8                   138
#define IDC_PEAKEFFECT_FALLANDRISE      138
#define IDC_STATICGREEN                 139
#define IDC_PEAKEFFECT_RISEFALL         139
#define IDC_PEAKEFFECT_SPARKS           140
#define IDC_PICKCOLOUR                  140
#define IDC_ALLRANDOM                   141
#define IDC_GROUPBOX9                   142
#define IDC_EFFECT_FADESHADOW           142
#define CM_CONFIG                       11842
#define CM_CLOSE                        11843
#define CM_ABOUT                        11844
#define CM_PROFILES                     11845

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         40000
#define _APS_NEXT_CONTROL_VALUE         143
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
